# Hugo
title = "Ovenjoy"
description = "OvenJoy is a versatile Bun library designed to simplify routing and middleware management in your web applications. With OvenJoy, you can effortlessly define and manage routes, apply middleware, and handle HTTP requests like a pro."
images = ['https://drive.google.com/uc?id=1tCDt1UE_2jkEC1vmfJ0n86p_IakDrWUH']
baseurl = "https://ovenjoy.shubhamlad.in/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
# disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 10
rssLimit = 10
summarylength = 20 # 70 (default)

# Multilingual
defaultContentLanguage = "en"
disableLanguages = ["de", "nl"]
defaultContentLanguageInSubdir = false

copyRight = "Copyright (c) 2023 Shubham Lad"

[params]
  # home page profile
  images = ['https://drive.google.com/uc?id=1tCDt1UE_2jkEC1vmfJ0n86p_IakDrWUH']
  title = 'Ovenjoy | Baking Delicious Web Servers with Bun'
  description = "OvenJoy is a versatile Bun library designed to simplify routing and middleware management in your web applications. With OvenJoy, you can effortlessly define and manage routes, apply middleware, and handle HTTP requests like a pro."

[outputs]
  home = ["HTML", "RSS", "searchIndex"]
  section = ["HTML", "RSS", "SITEMAP"]

[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

# Add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "30m"

[taxonomies]
  contributor = "contributors"
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/blog/:slug/"
  docs = "/docs/:sections[1:]/:slug/"
# docs = "/docs/1.0/:sections[1:]/:slug/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 100
    [[related.indices]]
    name = "tags"
    weight = 80
    [[related.indices]]
    name = "date"
    weight = 10

[imaging]
  anchor = "Smart"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 75
  resampleFilter = "Box"
