[[main]]
  name = "GitHub"
  url = "https://github.com/ShuLaPy/ovenjoy"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/shubhamlad/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://x.com/_shulapy"
  weight = 30
